###
//  -------------------      Auth   ------------------------
//  -------------------     Register   ------------------------
POST http://localhost:5000/api/users/
Content-Type: application/json

{   
    "emaisl": "alon@gmail.com",
    "password": "12345",
    "name": "NISIM"
}


###
//  -------------------  Login ------------------------
POST http://localhost:5000/api/users/login
Content-Type: application/json

{
    "is_child": true,
    "email": "1@gmail.com",
    "password": "1"
}

