###
//  -------------------      Auth   ------------------------
//  -------------------     Register   ------------------------
POST http://localhost:5000/api/users/
Content-Type: application/json

{   
    "email": "alon@gmail.com",
    "password": "12345",
    "name": "Alon"
}


###
//  -------------------  Login ------------------------
POST http://localhost:5000/api/users/login
Content-Type: application/json

{
    "email": "alon@gmail.com",
    "password": "12345"
}

###
//  -------------------  Me ------------------------
GET http://localhost:5000/api/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyOWUzYzA5ZGRkNDAzZjVlZDU5YjNjYSIsImlhdCI6MTY1NDUzODQxNCwiZXhwIjoxNjU1NDAyNDE0fQ.3aUajy19aop6uVTnImxvdnbB5_XYAMx1RdBxJKHDAIk
Content-Type: application/json


###
//  -------------------  Get Tickets ------------------------
GET http://localhost:5000/api/tickets/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyOWUzYzA5ZGRkNDAzZjVlZDU5YjNjYSIsImlhdCI6MTY3NTM0MDEyOCwiZXhwIjoxNjc2MjA0MTI4fQ.tj5BuxhNNp5DSSrYK_z4tMnfMAoyd4dBwFvLKLKN2No

{

}


###
//  -------------------  Get Ticket by ID ------------------------
GET http://localhost:5000/api/tickets/63dbb0b3f520a34bed94cb51
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyOWUzYzA5ZGRkNDAzZjVlZDU5YjNjYSIsImlhdCI6MTY3NTM0MDEyOCwiZXhwIjoxNjc2MjA0MTI4fQ.tj5BuxhNNp5DSSrYK_z4tMnfMAoyd4dBwFvLKLKN2No

{
}

###

//  -------------------  Update Ticket BY ID ------------------------
PUT http://localhost:5000/api/tickets/63dbb0b3f520a34bed94cb51
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyOWUzYzA5ZGRkNDAzZjVlZDU5YjNjYSIsImlhdCI6MTY3NTM0MDEyOCwiZXhwIjoxNjc2MjA0MTI4fQ.tj5BuxhNNp5DSSrYK_z4tMnfMAoyd4dBwFvLKLKN2No

{
    "product": "iPad",
    "description": "iPad not working now"
}

###


//  -------------------  Delete Ticket BY ID ------------------------
DELETE  http://localhost:5000/api/tickets/63dbb0b3f520a34bed94cb51
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyOWUzYzA5ZGRkNDAzZjVlZDU5YjNjYSIsImlhdCI6MTY3NTM0MDEyOCwiZXhwIjoxNjc2MjA0MTI4fQ.tj5BuxhNNp5DSSrYK_z4tMnfMAoyd4dBwFvLKLKN2No

{

}

###

//  -------------------  Create Ticket  ------------------------
POST http://localhost:5000/api/tickets/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyOWUzYzA5ZGRkNDAzZjVlZDU5YjNjYSIsImlhdCI6MTY3NTM0MDEyOCwiZXhwIjoxNjc2MjA0MTI4fQ.tj5BuxhNNp5DSSrYK_z4tMnfMAoyd4dBwFvLKLKN2No

{
    "product": "iPhone",
    "description": "Not turning on"
}

###
//  -------------------  Get Notes ------------------------
GET http://localhost:5000/api/tickets/63dbb0c0f520a34bed94cb55/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyOWUzYzA5ZGRkNDAzZjVlZDU5YjNjYSIsImlhdCI6MTY3NTM0MDEyOCwiZXhwIjoxNjc2MjA0MTI4fQ.tj5BuxhNNp5DSSrYK_z4tMnfMAoyd4dBwFvLKLKN2No

{

}

###
//  -------------------  Add Note ------------------------
POST http://localhost:5000/api/tickets/63dbb0c0f520a34bed94cb55/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyOWUzYzA5ZGRkNDAzZjVlZDU5YjNjYSIsImlhdCI6MTY3NTM0MDEyOCwiZXhwIjoxNjc2MjA0MTI4fQ.tj5BuxhNNp5DSSrYK_z4tMnfMAoyd4dBwFvLKLKN2No

{
    "text": "I need Help"
}